server:
  port: 80
  http2:
    enabled: true
  tomcat:
    uri-encoding: UTF-8
  static-location: web

bee:
  db:
    dbName: MySQL
    driverName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://devilspiderx.ltd:3306/aduiduidui?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: aduiduidui
    password: 123456
  osql:
    showSQL: false

logging:
  file:
    name: "${logging.file.path}/access.log"
    path: "./log"
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %p ${PID} --- [%t] %-40.40logger{39} [%4line] : %m%n"
  level:
    root: info
  charset:
    file: UTF-8
  logback:
    rollingpolicy:
      file-name-pattern: "${logging.file.path}/%d{yyyy-MM-dd}_%i.log"
      max-file-size: 10MB
      max-history: 7
