server:
  port: 80
  http2:
    enabled: true
  tomcat:
    uri-encoding: UTF-8
  static-location: web

bee:
  db:
    dbName: MySQL
    driverName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://devilspiderx.ltd:3306/aduiduidui?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: aduiduidui
    password: 123456
  osql:
    showSQL: false
